"""Add user details and session management

Revision ID: 987180427bb0
Revises: d5f6f4a885aa
Create Date: 2025-08-09 17:17:58.266780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987180427bb0'
down_revision: Union[str, Sequence[str], None] = 'd5f6f4a885aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('context_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('api_keys', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.add_column('chatbots', sa.Column('chatbot_config', sa.JSON(), nullable=True))
    op.add_column('chatbots', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('profile_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'profile_data')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'role')
    op.drop_column('users', 'company')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('chatbots', 'updated_at')
    op.drop_column('chatbots', 'chatbot_config')
    op.drop_column('api_keys', 'last_used')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
